"use client";
import { useState } from "react";
import { Download, Printer, X, ShieldCheck, Copy, Check, ExternalLink } from "lucide-react";

interface AwardDocument {
  document_type: string;
  reference: string;
  project_title: string;
  procurement_type: string;
  supplier_name: string;
  company_name: string;
  bid_amount: number;
  budget: number;
  award_date?: string;
  proceed_date?: string;
  resolution_date?: string;
  delivery_period: number;
  savings?: number | null;
  blockchain_tx_hash?: string | null;
}

function buildDocumentText(doc: AwardDocument) {
  const lines = [
    "E-PROCUREMENT SYSTEM",
    "===============================================",
    "",
    doc.document_type,
    "",
    `Reference: ${doc.reference}`,
    `Project Title: ${doc.project_title}`,
    `Procurement Type: ${doc.procurement_type}`,
    `Awarded Supplier: ${doc.supplier_name}`,
    `Company Name: ${doc.company_name}`,
    `Bid Amount: \u20B1${Number(doc.bid_amount || 0).toLocaleString()}`,
    `Project Budget: \u20B1${Number(doc.budget || 0).toLocaleString()}`,
    `Award Date: ${doc.award_date || doc.proceed_date || doc.resolution_date || "-"}`,
    `Delivery Period: ${doc.delivery_period} days`,
  ];
  if (doc.savings != null) lines.push(`Budget Savings: \u20B1${Number(doc.savings).toLocaleString()}`);
  if (doc.blockchain_tx_hash) {
    lines.push(`Blockchain Tx Hash: ${doc.blockchain_tx_hash}`);
    lines.push("Verification Status: Anchored & Verified on Blockchain");
  }
  lines.push("", "This document is electronically generated by the E-Procurement System.", "");
  return lines.join("\n");
}

export default function AwardDocumentModal({ isOpen, onClose, document: doc }: { isOpen: boolean; onClose: () => void; document: AwardDocument | null }) {
  const [copied, setCopied] = useState(false);

  if (!isOpen || !doc) return null;

  function handlePrint() { window.print(); }

  function handleDownload() {
    const blob = new Blob([buildDocumentText(doc!)], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = window.document.createElement("a");
    link.href = url;
    link.download = `${String(doc!.document_type || "award_document").replace(/\s+/g, "_").toLowerCase()}.txt`;
    window.document.body.appendChild(link);
    link.click();
    window.document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  const handleCopy = async () => {
    if (!doc?.blockchain_tx_hash) return;
    try {
      await navigator.clipboard.writeText(doc.blockchain_tx_hash);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy text: ", err);
    }
  };

  const dateDisplay = doc.award_date || doc.proceed_date || doc.resolution_date || "-";

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-4 backdrop-blur-sm">
      <div className="w-full max-w-2xl overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-2xl">
        <div className="flex items-center justify-between border-b border-slate-100 px-6 py-4">
          <div>
            <h3 className="text-base font-semibold text-slate-900">{doc.document_type}</h3>
            <p className="mt-0.5 text-xs text-slate-400">Reference: {doc.reference}</p>
          </div>
          <div className="flex items-center gap-2">
            <button onClick={handleDownload} className="flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm font-medium text-slate-600 transition-colors hover:bg-slate-50"><Download className="h-4 w-4" /> Download</button>
            <button onClick={handlePrint} className="flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm font-medium text-slate-600 transition-colors hover:bg-slate-50"><Printer className="h-4 w-4" /> Print</button>
            <button onClick={onClose} className="flex h-8 w-8 items-center justify-center rounded-lg text-slate-400 transition-colors hover:bg-slate-100"><X className="h-4 w-4" /></button>
          </div>
        </div>

        <div className="space-y-4 px-8 py-6 print:px-0">
          <div className="border-b border-slate-100 pb-4 text-center">
            <p className="text-sm font-bold uppercase tracking-wide text-slate-900">Republic of the Philippines</p>
            <p className="mt-1 text-xs text-slate-500">E-Procurement System</p>
            <h2 className="mt-3 text-lg font-bold uppercase text-slate-900">{doc.document_type}</h2>
            <p className="mt-1 text-xs text-slate-400">{doc.reference}</p>
          </div>

          <div className="space-y-3">
            <div className="grid grid-cols-2 gap-4">
              {[
                { label: "Project Title", value: doc.project_title },
                { label: "Procurement Type", value: doc.procurement_type },
                { label: "Awarded Supplier", value: doc.supplier_name },
                { label: "Company Name", value: doc.company_name },
                { label: "Bid Amount", value: `\u20B1${Number(doc.bid_amount || 0).toLocaleString()}` },
                { label: "Project Budget", value: `\u20B1${Number(doc.budget || 0).toLocaleString()}` },
                { label: "Award Date", value: dateDisplay },
                { label: "Delivery Period", value: `${doc.delivery_period} days` },
              ].map(({ label, value }) => (
                <div key={label} className="rounded-xl bg-slate-50 p-3">
                  <p className="mb-0.5 text-xs text-slate-400">{label}</p>
                  <p className="text-sm font-semibold text-slate-800">{value}</p>
                </div>
              ))}
            </div>

            {doc.savings != null && (
              <div className="rounded-xl border border-emerald-100 bg-emerald-50 p-3">
                <p className="mb-0.5 text-xs text-emerald-600">Budget Savings</p>
                <p className="text-sm font-bold text-emerald-700">{"\u20B1"}{Number(doc.savings).toLocaleString()}</p>
              </div>
            )}

            {doc.blockchain_tx_hash && (
              <div className="rounded-xl border border-blue-100 bg-blue-50/70 p-3.5 flex flex-col gap-2">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <div className="flex h-6 w-6 items-center justify-center rounded-lg bg-blue-100">
                      <ShieldCheck className="h-4 w-4 text-blue-600" />
                    </div>
                    <span className="text-xs font-semibold text-blue-800">Anchored in Blockchain</span>
                  </div>
                  <span className="inline-flex items-center rounded-full bg-blue-100/60 px-2 py-0.5 text-[10px] font-medium text-blue-800">
                    Verified
                  </span>
                </div>
                <div className="flex items-center justify-between gap-3 bg-white/80 border border-blue-100/50 rounded-lg p-2">
                  <span className="font-mono text-xs text-slate-600 break-all select-all pr-2">
                    {doc.blockchain_tx_hash}
                  </span>
                  <div className="flex items-center gap-1.5 shrink-0">
                    <button
                      onClick={handleCopy}
                      className="flex items-center gap-1 rounded-md border border-slate-200 bg-white px-2 py-1 text-[11px] font-medium text-slate-600 transition-colors hover:bg-slate-50 active:bg-slate-100"
                      title="Copy Transaction Hash"
                    >
                      {copied ? (
                        <>
                          <Check className="h-3.5 w-3.5 text-emerald-500" />
                          <span className="text-emerald-600 font-semibold">Copied</span>
                        </>
                      ) : (
                        <>
                          <Copy className="h-3.5 w-3.5 text-slate-400" />
                          <span>Copy</span>
                        </>
                      )}
                    </button>
                    <a
                      href={`https://sepolia.basescan.org/tx/${doc.blockchain_tx_hash}`}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="flex items-center gap-1 rounded-md border border-slate-200 bg-white px-2.5 py-1 text-[11px] font-medium text-slate-600 transition-colors hover:bg-slate-50 active:bg-slate-100"
                      title="View on Basescan"
                    >
                      <ExternalLink className="h-3.5 w-3.5 text-slate-400" />
                      <span>Explorer</span>
                    </a>
                  </div>
                </div>
              </div>
            )}
          </div>

          <div className="mt-8 border-t border-slate-100 pt-4">
            <div className="grid grid-cols-2 gap-8">
              <div>
                <div className="mb-1 border-b border-slate-300 pb-8" />
                <p className="text-xs font-semibold text-slate-700">Bids and Awards Committee Chairman</p>
                <p className="text-xs text-slate-400">Signature over printed name</p>
              </div>
              <div>
                <div className="mb-1 border-b border-slate-300 pb-8" />
                <p className="text-xs font-semibold text-slate-700">{doc.supplier_name}</p>
                <p className="text-xs text-slate-400">Authorized Representative</p>
              </div>
            </div>
          </div>

          <p className="mt-4 text-right text-xs text-slate-400">Issued on: {dateDisplay}</p>
        </div>
      </div>
    </div>
  );
}
