# Generated by Django 5.1.7 on 2026-05-08 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auditlog_documentupload_procurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentupload',
            name='file_path',
        ),
        migrations.AddField(
            model_name='documentupload',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='project',
            name='delivery_period',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='procurement_type',
            field=models.CharField(choices=[('Goods', 'Goods'), ('Infrastructure', 'Infrastructure'), ('Consulting', 'Consulting'), ('Services', 'Services')], default='Services', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='technical_specifications',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Awarded', 'Awarded'), ('Cancelled', 'Cancelled')], default='Active', max_length=20),
        ),
    ]
