# Generated by Django 5.1.7 on 2026-05-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_procurement_review_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='awarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
