# Generated by Copilot for project archiving

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_procurement_public_result_expiry_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="archived_reason",
            field=models.CharField(blank=True, help_text="Reason for archiving this project", max_length=255, null=True),
        ),
    ]