# Generated by migration to add procurement_schedule to Project

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_project_archive_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="procurement_schedule",
            field=models.DateField(blank=True, null=True),
        ),
    ]