# Generated by Django 5.1.7 on 2026-05-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_add_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentupload',
            name='document_type',
            field=models.CharField(choices=[('Legal Documents', 'Legal Documents'), ('Business Permit', 'Business Permit'), ('PhilGEPS Registration', 'PhilGEPS Registration'), ('Tax Clearance', 'Tax Clearance'), ('Valid ID', 'Valid ID'), ('Quotation', 'Quotation'), ('Supporting Documents', 'Supporting Documents')], max_length=50),
        ),
    ]
