# Generated by Django 5.1.7 on 2026-05-15 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('new_supplier', 'New Supplier Registered'), ('supplier_approved', 'Supplier Approved'), ('supplier_rejected', 'Supplier Rejected'), ('new_bid', 'New Bid Submitted'), ('project_approved', 'Project Approved — New Bidding'), ('project_rejected', 'Project Rejected'), ('winner_selected', 'Winner Selected'), ('blockchain_recorded', 'Blockchain Recorded'), ('revision_required', 'Revision Required'), ('new_procurement_request', 'New Procurement Request')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
