# Generated by Django 5.1.7 on 2026-05-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='resource_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('project', 'Project'), ('bid', 'Bid'), ('request', 'Procurement Request'), ('supplier', 'Supplier'), ('user', 'User')], max_length=50, null=True),
        ),
    ]
