# Generated by Django 5.1.7 on 2026-05-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_rename_notification_type_add_link_related_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_supplier', 'New Supplier Registration'), ('supplier_approved', 'Supplier Approved'), ('supplier_rejected', 'Supplier Rejected'), ('new_bid', 'New Bid Submitted'), ('bid_won', 'Bid Won'), ('bid_lost', 'Bid Lost'), ('project_published', 'Project Published'), ('project_awarded', 'Project Awarded'), ('procurement_request', 'New Procurement Request'), ('request_approved', 'Procurement Request Approved'), ('request_rejected', 'Procurement Request Rejected'), ('winner_selected', 'Winner Selected')], max_length=50),
        ),
    ]
