import { Download, Printer, X } from 'lucide-react';

function buildDocumentText(document) {
  const lines = [
    'BLOCKCHAIN E-PROCUREMENT SYSTEM',
    '===============================================',
    '',
    document.document_type,
    '',
    `Reference: ${document.reference}`,
    `Project Title: ${document.project_title}`,
    `Procurement Type: ${document.procurement_type}`,
    `Awarded Supplier: ${document.supplier_name}`,
    `Company Name: ${document.company_name}`,
    `Bid Amount: ₱${Number(document.bid_amount || 0).toLocaleString()}`,
    `Project Budget: ₱${Number(document.budget || 0).toLocaleString()}`,
    `Award Date: ${document.award_date || document.proceed_date || document.resolution_date || '-'}`,
    `Delivery Period: ${document.delivery_period} days`,
  ];

  if (document.savings !== undefined && document.savings !== null) {
    lines.push(`Budget Savings: ₱${Number(document.savings).toLocaleString()}`);
  }

  lines.push('', 'This document is electronically generated by the Blockchain E-Procurement System.', '');
  return lines.join('\n');
}

export default function AwardDocumentModal({ isOpen, onClose, document }) {
  if (!isOpen || !document) return null;

  function handlePrint() {
    window.print();
  }

  function handleDownload() {
    const blob = new Blob([buildDocumentText(document)], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = window.document.createElement('a');
    link.href = url;
    link.download = `${String(document.document_type || 'award_document').replace(/\s+/g, '_').toLowerCase()}.txt`;
    window.document.body.appendChild(link);
    link.click();
    window.document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-4 backdrop-blur-sm">
      <div className="w-full max-w-2xl overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-2xl">
        <div className="flex items-center justify-between border-b border-slate-100 px-6 py-4">
          <div>
            <h3 className="text-base font-semibold text-slate-900">{document.document_type}</h3>
            <p className="mt-0.5 text-xs text-slate-400">Reference: {document.reference}</p>
          </div>
          <div className="flex items-center gap-2">
            <button onClick={handleDownload} className="flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm font-medium text-slate-600 transition-colors hover:bg-slate-50">
              <Download className="h-4 w-4" /> Download
            </button>
            <button onClick={handlePrint} className="flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm font-medium text-slate-600 transition-colors hover:bg-slate-50">
              <Printer className="h-4 w-4" /> Print
            </button>
            <button onClick={onClose} className="flex h-8 w-8 items-center justify-center rounded-lg text-slate-400 transition-colors hover:bg-slate-100">
              <X className="h-4 w-4" />
            </button>
          </div>
        </div>

        <div className="space-y-4 px-8 py-6 print:px-0">
          <div className="border-b border-slate-100 pb-4 text-center">
            <p className="text-sm font-bold uppercase tracking-wide text-slate-900">Republic of the Philippines</p>
            <p className="mt-1 text-xs text-slate-500">Blockchain-Based E-Procurement System</p>
            <h2 className="mt-3 text-lg font-bold uppercase text-slate-900">{document.document_type}</h2>
            <p className="mt-1 text-xs text-slate-400">{document.reference}</p>
          </div>

          <div className="space-y-3">
            <div className="grid grid-cols-2 gap-4">
              {[
                { label: 'Project Title', value: document.project_title },
                { label: 'Procurement Type', value: document.procurement_type },
                { label: 'Awarded Supplier', value: document.supplier_name },
                { label: 'Company Name', value: document.company_name },
                { label: 'Bid Amount', value: `₱${Number(document.bid_amount || 0).toLocaleString()}` },
                { label: 'Project Budget', value: `₱${Number(document.budget || 0).toLocaleString()}` },
                { label: 'Award Date', value: document.award_date || document.proceed_date || document.resolution_date || '-' },
                { label: 'Delivery Period', value: `${document.delivery_period} days` },
              ].map(({ label, value }) => (
                <div key={label} className="rounded-xl bg-slate-50 p-3">
                  <p className="mb-0.5 text-xs text-slate-400">{label}</p>
                  <p className="text-sm font-semibold text-slate-800">{value}</p>
                </div>
              ))}
            </div>

            {document.savings !== undefined && document.savings !== null && (
              <div className="rounded-xl border border-emerald-100 bg-emerald-50 p-3">
                <p className="mb-0.5 text-xs text-emerald-600">Budget Savings</p>
                <p className="text-sm font-bold text-emerald-700">₱{Number(document.savings).toLocaleString()}</p>
              </div>
            )}
          </div>

          <div className="mt-8 border-t border-slate-100 pt-4">
            <div className="grid grid-cols-2 gap-8">
              <div>
                <div className="mb-1 border-b border-slate-300 pb-8" />
                <p className="text-xs font-semibold text-slate-700">Bids and Awards Committee Chairman</p>
                <p className="text-xs text-slate-400">Signature over printed name</p>
              </div>
              <div>
                <div className="mb-1 border-b border-slate-300 pb-8" />
                <p className="text-xs font-semibold text-slate-700">{document.supplier_name}</p>
                <p className="text-xs text-slate-400">Authorized Representative</p>
              </div>
            </div>
          </div>

          <p className="mt-4 text-right text-xs text-slate-400">Issued on: {document.award_date || document.proceed_date || document.resolution_date || '-'}</p>
        </div>
      </div>
    </div>
  );
}
