# Generated by Django 5.1.7 on 2026-05-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_fix_default_admin_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_permit_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
