# Generated by Django 5.2.6 on 2026-04-26 01:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bids', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('hash', models.TextField(unique=True)),
                ('project_ref_id', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_records', to='bids.bid')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_records', to='projects.project')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
