# Generated by Django 5.1.7 on 2026-05-12 09:50

from django.db import migrations, models


def map_bid_statuses(apps, schema_editor):
    Bid = apps.get_model("bids", "Bid")
    status_map = {
        "Submitted": "submitted",
        "Under Review": "under_evaluation",
        "Selected": "won",
        "Rejected": "lost",
    }
    for bid in Bid.objects.all():
        next_status = status_map.get(bid.status, bid.status)
        if next_status != bid.status:
            Bid.objects.filter(pk=bid.pk).update(status=next_status)


def restore_bid_statuses(apps, schema_editor):
    Bid = apps.get_model("bids", "Bid")
    status_map = {
        "submitted": "Submitted",
        "under_evaluation": "Under Review",
        "won": "Selected",
        "lost": "Rejected",
    }
    for bid in Bid.objects.all():
        next_status = status_map.get(bid.status, bid.status)
        if next_status != bid.status:
            Bid.objects.filter(pk=bid.pk).update(status=next_status)


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_bid_company_name_bid_evaluation_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='quotation_file',
            field=models.FileField(blank=True, null=True, upload_to='bids/quotations/'),
        ),
        migrations.AddField(
            model_name='bid',
            name='supporting_documents',
            field=models.FileField(blank=True, null=True, upload_to='bids/documents/'),
        ),
        migrations.AddField(
            model_name='bid',
            name='technical_proposal',
            field=models.FileField(blank=True, null=True, upload_to='bids/proposals/'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bid',
            name='proposal',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_evaluation', 'Under Evaluation'), ('won', 'Won'), ('lost', 'Lost')], default='submitted', max_length=50),
        ),
        migrations.RunPython(map_bid_statuses, restore_bid_statuses),
    ]
