# Generated by Django 5.1.7 on 2026-05-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_bid_quotation_file_bid_supporting_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='technical_compliance',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
