from django.urls import path

from .views import (
    ProjectListCreateView,
    ProjectDetailView,
    PublishProjectView,
    ProjectHistoryView,
    ArchiveProjectView,
    UnarchiveProjectView,
    ProcurementRequestListCreateView,
    ProcurementRequestDetailView,
    ProcurementRequestReviewView,
    ApproveProcurementRequestView,
    RejectProcurementRequestView,
    ReturnForRevisionView,
    AuditLogListView,
    DocumentUploadListCreateView,
    PublicResultsView,
    PublicProjectStatsView,
)

urlpatterns = [
    path("", ProjectListCreateView.as_view(), name="project-list-create"),
    path("history/", ProjectHistoryView.as_view(), name="project-history"),
    path("<uuid:pk>/archive/", ArchiveProjectView.as_view(), name="project-archive"),
    path("<uuid:pk>/unarchive/", UnarchiveProjectView.as_view(), name="project-unarchive"),
    path("<uuid:pk>/", ProjectDetailView.as_view(), name="project-detail"),
    path("<uuid:pk>/publish/", PublishProjectView.as_view(), name="project-publish"),
    path("procurements/", ProcurementRequestListCreateView.as_view(), name="procurement-list-create"),
    path("procurements/<uuid:pk>/", ProcurementRequestDetailView.as_view(), name="procurement-detail"),
    path("procurements/<uuid:pk>/approve/", ApproveProcurementRequestView.as_view(), name="procurement-approve"),
    path("procurements/<uuid:pk>/reject/", RejectProcurementRequestView.as_view(), name="procurement-reject"),
    path("procurements/<uuid:pk>/revise/", ReturnForRevisionView.as_view(), name="procurement-revise"),
    path("requests/", ProcurementRequestListCreateView.as_view(), name="request-list-create"),
    path("requests/<uuid:pk>/", ProcurementRequestDetailView.as_view(), name="request-detail"),
    path("requests/<uuid:pk>/review/", ProcurementRequestReviewView.as_view(), name="request-review"),
    path("requests/<uuid:pk>/approve/", ApproveProcurementRequestView.as_view(), name="request-approve"),
    path("requests/<uuid:pk>/reject/", RejectProcurementRequestView.as_view(), name="request-reject"),
    path("requests/<uuid:pk>/revise/", ReturnForRevisionView.as_view(), name="request-revise"),
    path("audit-logs/", AuditLogListView.as_view(), name="audit-log-list"),
    path("documents/", DocumentUploadListCreateView.as_view(), name="document-upload-list-create"),
    path("public/results/", PublicResultsView.as_view(), name="public-results"),
    path("public/stats/", PublicProjectStatsView.as_view(), name="public-project-stats"),
]
